load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "simtest_lib",
    srcs = ["main.go"],
    importpath = "github.com/AshrithaG/raft-control-plane/cmd/simtest",
    visibility = ["//visibility:private"],
    deps = [
        "//kv",
        "//lincheck",
        "//raft",
        "//sim",
    ],
)

go_binary(
    name = "simtest",
    embed = [":simtest_lib"],
    visibility = ["//visibility:public"],
)
